export const apiEndpoints = {
    auth: {
        login: '/v1/auth/login',
        logout: '/v1/auth/logout',
        me: '/v1/auth/me',
    },
    users: {
        create: '/v1/users',
        list: '/v1/users',
        get: '/v1/users/:id',
        update: '/v1/users/:id',
        delete: '/v1/users/:id',
    },
    departments: {
        create: '/v1/departments',
        list: '/v1/departments',
        get: '/v1/departments/:id',
        update: '/v1/departments/:id',
        delete: '/v1/departments/:id',
    },
    media: {
        presignUpload: '/v1/media/presign-upload',
        create: '/v1/media',
        list: '/v1/media',
        get: '/v1/media/:id',
        update: '/v1/media/:id',
        delete: '/v1/media/:id',
    },
    presentations: {
        create: '/v1/presentations',
        list: '/v1/presentations',
        get: '/v1/presentations/:id',
        update: '/v1/presentations/:id',
        delete: '/v1/presentations/:id',
    },
    schedules: {
        create: '/v1/schedules',
        list: '/v1/schedules',
        get: '/v1/schedules/:id',
        update: '/v1/schedules/:id',
        delete: '/v1/schedules/:id',
        publish: '/v1/schedules/:id/publish',
    },
    screens: {
        create: '/v1/screens',
        list: '/v1/screens',
        get: '/v1/screens/:id',
        update: '/v1/screens/:id',
        delete: '/v1/screens/:id',
    },
    requests: {
        create: '/v1/requests',
        list: '/v1/requests',
        get: '/v1/requests/:id',
        update: '/v1/requests/:id',
        delete: '/v1/requests/:id',
    },
    notifications: {
        create: '/v1/notifications',
        list: '/v1/notifications',
        get: '/v1/notifications/:id',
        update: '/v1/notifications/:id',
        delete: '/v1/notifications/:id',
    },
    auditLogs: {
        list: '/v1/audit-logs',
        get: '/v1/audit-logs/:id',
    },
    devicePairing: {
        create: '/v1/device-pairing',
        list: '/v1/device-pairing',
        get: '/v1/device-pairing/:id',
        update: '/v1/device-pairing/:id',
        delete: '/v1/device-pairing/:id',
    },
    deviceTelemetry: {
        heartbeat: '/v1/device/heartbeat',
        proofOfPlay: '/v1/device/proof-of-play',
        screenshot: '/v1/device/screenshot',
        commands: '/v1/device/:deviceId/commands',
        ackCommand: '/v1/device/:deviceId/commands/:commandId/ack',
    },
    emergency: {
        create: '/v1/emergency',
        list: '/v1/emergency',
        get: '/v1/emergency/:id',
        update: '/v1/emergency/:id',
        delete: '/v1/emergency/:id',
    },
    apiKeys: {
        create: '/v1/api-keys',
        list: '/v1/api-keys',
        get: '/v1/api-keys/:id',
        update: '/v1/api-keys/:id',
        delete: '/v1/api-keys/:id',
    },
    webhooks: {
        create: '/v1/webhooks',
        list: '/v1/webhooks',
        get: '/v1/webhooks/:id',
        update: '/v1/webhooks/:id',
        delete: '/v1/webhooks/:id',
    },
    ssoConfig: {
        create: '/v1/sso-config',
        list: '/v1/sso-config',
        get: '/v1/sso-config/:id',
        update: '/v1/sso-config/:id',
        delete: '/v1/sso-config/:id',
    },
    settings: {
        get: '/v1/settings',
        update: '/v1/settings',
    },
    conversations: {
        create: '/v1/conversations',
        list: '/v1/conversations',
        get: '/v1/conversations/:id',
        update: '/v1/conversations/:id',
        delete: '/v1/conversations/:id',
    },
    proofOfPlay: {
        list: '/v1/proof-of-play',
        export: '/v1/proof-of-play/export',
    },
    metrics: {
        overview: '/v1/metrics/overview',
    },
    reports: {
        summary: '/v1/reports/summary',
    },
    userInvite: {
        create: '/v1/users/invite',
        list: '/v1/users/invite',
        get: '/v1/users/invite/:id',
        update: '/v1/users/invite/:id',
        delete: '/v1/users/invite/:id',
    },
    userActivate: {
        create: '/v1/users/activate',
        list: '/v1/users/activate',
        get: '/v1/users/activate/:id',
        update: '/v1/users/activate/:id',
        delete: '/v1/users/activate/:id',
    },
};
