export const apiEndpoints = {
  auth: {
    login: '/v1/auth/login',
    logout: '/v1/auth/logout',
    me: '/v1/auth/me',
  },
  users: {
    create: '/v1/users',
    list: '/v1/users',
    get: '/v1/users/:id',
    update: '/v1/users/:id',
    delete: '/v1/users/:id',
  },
  userInvite: {
    invite: '/v1/users/invite',
    resetPassword: '/v1/users/:id/reset-password',
  },
  userActivate: {
    activate: '/v1/users/activate',
  },
  departments: {
    create: '/v1/departments',
    list: '/v1/departments',
    get: '/v1/departments/:id',
    update: '/v1/departments/:id',
    delete: '/v1/departments/:id',
  },
  media: {
    presignUpload: '/v1/media/presign-upload',
    create: '/v1/media',
    list: '/v1/media',
    get: '/v1/media/:id',
    complete: '/v1/media/:id/complete',
  },
  presentations: {
    create: '/v1/presentations',
    list: '/v1/presentations',
    get: '/v1/presentations/:id',
    update: '/v1/presentations/:id',
    delete: '/v1/presentations/:id',
  },
  schedules: {
    create: '/v1/schedules',
    list: '/v1/schedules',
    get: '/v1/schedules/:id',
    update: '/v1/schedules/:id',
    publish: '/v1/schedules/:id/publish',
    publishes: '/v1/schedules/:id/publishes',
    updatePublishTarget: '/v1/publishes/:publishId/targets/:targetId',
    publishStatus: '/v1/publishes/:id',
  },
  screens: {
    create: '/v1/screens',
    list: '/v1/screens',
    get: '/v1/screens/:id',
    update: '/v1/screens/:id',
    delete: '/v1/screens/:id',
  },
  requests: {
    create: '/v1/requests',
    list: '/v1/requests',
    get: '/v1/requests/:id',
    update: '/v1/requests/:id',
    addMessage: '/v1/requests/:id/messages',
    listMessages: '/v1/requests/:id/messages',
  },
  notifications: {
    list: '/v1/notifications',
    get: '/v1/notifications/:id',
    markRead: '/v1/notifications/:id/read',
    markAllRead: '/v1/notifications/read-all',
    delete: '/v1/notifications/:id',
  },
  auditLogs: {
    list: '/v1/audit-logs',
    get: '/v1/audit-logs/:id',
  },
  apiKeys: {
    create: '/v1/api-keys',
    list: '/v1/api-keys',
    rotate: '/v1/api-keys/:id/rotate',
    revoke: '/v1/api-keys/:id/revoke',
  },
  deviceTelemetry: {
    heartbeat: '/v1/device/heartbeat',
    proofOfPlay: '/v1/device/proof-of-play',
    screenshot: '/v1/device/screenshot',
    commands: '/v1/device/:deviceId/commands',
    ackCommand: '/v1/device/:deviceId/commands/:commandId/ack',
  },
  devicePairing: {
    generate: '/v1/device-pairing/generate',
    complete: '/v1/device-pairing/complete',
    list: '/v1/device-pairing',
  },
  emergency: {
    trigger: '/v1/emergency/trigger',
    status: '/v1/emergency/status',
    clear: '/v1/emergency/:id/clear',
    history: '/v1/emergency/history',
  },
  webhooks: {
    create: '/v1/webhooks',
    list: '/v1/webhooks',
    update: '/v1/webhooks/:id',
    delete: '/v1/webhooks/:id',
    test: '/v1/webhooks/:id/test',
  },
  ssoConfig: {
    upsert: '/v1/sso-config',
    list: '/v1/sso-config',
    deactivate: '/v1/sso-config/:id/deactivate',
  },
  settings: {
    list: '/v1/settings',
    upsert: '/v1/settings',
  },
  conversations: {
    start: '/v1/conversations',
    list: '/v1/conversations',
    listMessages: '/v1/conversations/:id/messages',
    sendMessage: '/v1/conversations/:id/messages',
    markRead: '/v1/conversations/:id/read',
  },
  proofOfPlay: {
    list: '/v1/proof-of-play',
    export: '/v1/proof-of-play/export',
  },
  metrics: {
    overview: '/v1/metrics/overview',
  },
  reports: {
    summary: '/v1/reports/summary',
    trends: '/v1/reports/trends',
    requestsByDepartment: '/v1/reports/requests-by-department',
    offlineScreens: '/v1/reports/offline-screens',
    storage: '/v1/reports/storage',
    systemHealth: '/v1/reports/system-health',
  },
};

export const PENDINGSTATUS = 'PENDING';
